### PR TITLE
Fix test failure, #44 and #48

### PR DESCRIPTION
**Pull request by dukedhx**
- Implement [#44](https://github.com/Autodesk-Forge/forge-api-nodejs-client/issues/44)
- Fix [#48](https://github.com/Autodesk-Forge/forge-api-nodejs-client/issues/48)
- Forge Node.js SDK requires a string array of object id to extract geometry from a source file (https://github.com/Autodesk-Forge/forge-api-nodejs-client/blob/master/docs/JobObjOutputPayloadAdvanced.md ). But forge returned a message that the data format was wrong.So I check model derivative API document(https://forge.autodesk.com/en/docs/model-derivative/v2/reference/http/job-POST/ ). According to the document, I have to send integer array of object id to extract geometry from a source file.

### CODE REVIEW

**Comment by dukedhx** [comment]
**Test passed for node v6:**
image

**Comment by cyrillef** [comment]
Missed that one while doing my own updates - ignoring this pull request unfortunately :(

**Comment by dukedhx** [comment]
You can always do a merge - RESPECT other’s work pls.

**Comment by cyrillef** [comment]
Done

**Pull request merged**
